FROM python:3.11-slim

ARG POSTGRES_DATABASE_HOST
ARG POSTGRES_DATABASE_NAME
ARG POSTGRES_DATABASE_USERNAME
ARG POSTGRES_DATABASE_PASSWORD

WORKDIR /app

COPY . .

ENV POETRY_VERSION 1.6.1

ENV POSTGRES_DATABASE_HOST ${POSTGRES_DATABASE_HOST}
ENV POSTGRES_DATABASE_NAME ${POSTGRES_DATABASE_NAME}
ENV POSTGRES_DATABASE_USERNAME ${POSTGRES_DATABASE_USERNAME}
ENV POSTGRES_DATABASE_PASSWORD ${POSTGRES_DATABASE_PASSWORD}

RUN apt-get update && apt-get install -y curl gcc && apt-get clean
RUN pip install --no-cache-dir --upgrade -r requirements.txt
RUN pip install "poetry==${POETRY_VERSION}"

CMD ["./scripts/run.sh"]
