# Use postgres/example user/password credentials
version: '3.1'

networks:
  postgres_net:
    name: postgres_net

services:

  postgres:
    image: postgres
    networks:
      - postgres_net
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dumpuser_service
    ports:
      - 5432:5432

  # scheduler:
  #   build:
  #     dockerfile: deployment/scheduler.Dockerfile
  #   networks:
  #     - postgres_net
  #   restart: always
  #   depends_on:
  #     - postgres
  #   links:
  #     - postgres
