jobs:
  - job: sast_analysis
    displayName: Static Application Security Testing
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.10'
        displayName: 'Use Python 3.10'

      - script: |
           pip install pytest 
           pip install pytest-cov 
           pip install pytest-xdist 
           pip install pytest-bdd 
        displayName: 'Install a bunch of pip packages.'

      - task: SonarCloudPrepare@1
        displayName: 'Prepare analysis on SonarCloud'
        inputs:
          organization: 'ntd-dxc-sonarcloud'
          scannerMode: MSBuild
          projectKey: ntd-dxc-sonarclou
          projectName: ntd-dxc-sonarcloud


      - task: SonarCloudAnalyze@1
        displayName: 'Run Sonarcloud Analysis'
