stages:
  - stage: build_push_image
    jobs:
      - job: build_push_image_job
        displayName: Build and push image to acr
        steps:
          - script: |
              VERSION_LABELS="$(echo $(Build.SourceVersion) | cut -c1-7)"
              echo "##vso[task.setvariable variable=VERSION_LABELS;isOutput=true]${VERSION_LABELS}"
            displayName: Setup Version Labels
            name: versionLabels

          - task: Docker@2
            displayName: Build
            inputs:
              command: build
              containerRegistry: ntuc-cr-ntd
              repository: dumpuser-service
              Dockerfile: Dockerfile
              tags: |
                $(versionLabels.VERSION_LABELS)

          - task: Docker@2
            displayName: Push
            inputs:
              command: push
              containerRegistry: ntuc-cr-ntd
              repository: dumpuser-service
              tags: |
                $(versionLabels.VERSION_LABELS)
