jobs:
  - job: linter_check
    displayName: Flake8 Linter
    steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
      displayName: 'Use Python 3.10'

    - script: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "##vso[task.setvariable variable=PATH]${PATH}$HOME/.local/bin"
        poetry install --no-root
      displayName: Install dependencies

    - script: |
        poetry run flake8 .
      displayName: 'Linter'
